# Generated by Django 5.0.4 on 2024-12-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_monitoring_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Karta'), ('cash', 'Naqt')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
